### ISSUE TITLE
[SUGGESTION] browsing the internet

### ISSUE THREAD

**Issue by KianWalsh** [1j01/98#76]
I LOVE this project, and want to actually do classwork using it, but I wish you could go to websites other than the preset archive.org sites. It would break the emersion, but a toggelable browser setting in the browser window to allow the browser to work with other sites would be amazing.

it could be very easily done with a toggle menu, which if enabled, disables line 286 of explorer.js

**Comment by AliAkczaa** [comment]
how can i modify the code to make each page work?

**Comment by 1j01** [comment]
This is definitely something I'm interested in. The archive.org integration was actually spurned by most popular sites not working, but it seemed like a good fit (for a quick solution) since it fits with the retro theme to show historical versions.

Another tool, which I haven't looked into: https://github.com/dosyago/BrowserBoxhttps://github.com/dosyago/BrowserBox
I'd _guess_ x-frame-bypass fits the bill better.

It seems like the main hurdle will be hosting, in any case.
(I also thought about adding support in Electron with `<webview>`, but that's just much less interesting, if you'd have to download software to run it.)
